import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topbar from "./components/topbar";
import AuthProvider from "./context/auth/auth-provider";
import { supabaseServerComponent } from "@/lib/supabase/server";
import { themeStyle } from "@/ui/theme/config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await supabaseServerComponent();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  console.log("user in layout", user?.email)
  return (
    <html lang="en">
        <body  style={themeStyle}  
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
      <AuthProvider 
        initialUserEmail={user?.email}
      >
        <Topbar />
          {children}
      </AuthProvider>
        </body>
    </html>
  );
}
