import { Song } from "@/types/songs";

export const SONGS: Song[] = [
  {
    slug: "nothing-else-matters",
    title: "Nothing Else Matters",
    artist: "Metallica",
    youtubeId: "tAGnKpE4NCI",
    lines: [
      {
        t: "0.0",
        en: "So close, no matter how far...",
        ph: "so klouz, no metır hav far",
        tr: "Ne kadar uzak olsak da çok yakınız",
      },
      {
        t: "1.6",
        en: "Couldn't be much more from the heart",
        ph: "kudınt bi maç mor from dı hart",
        tr: "Daha kalpten olamazdı",
      },
      {
        t: "1.11",
        en: "Forever trusting who we are",
        ph: "forevır çırasting hu wi ar",
        tr: "Kim olduğumuza sonsuz güvenerek",
      },
      {
        t: "1.15",
        en: "And nothing else matters",
        ph: "end nating els metırz",
        tr: "Ve gerisi önemsiz",
      },
      {
        t: "1.23",
        en: "Never opened myself this way",
        ph: "Never opend myself tis vey",
        tr: "Ne yaptıkları umurumda olmadı",
      },

      {
        t: "1.28",
        en: "Life is ours, we live it our way",
        tr: "Hayat bizim, onu kendi yolumuzla yaşarız",
        ph: "Layf iz aorz, vi liv it aur vey",
      },
      {
        t: "1.33",
        en: "All these words, I don't just say",
        tr: "Bu sözlerin hepsi, sadece söylemiyorum",
        ph: "Ol diz vördz, ay dont cast sey",
      },
      {
        t: "1.38",
        en: "And nothing else matters",
        tr: "Ve başka hiçbir şey önemli değil",
        ph: "End nathing els metırz",
      },

      {
        t: "1.46",
        en: "Trust I seek and I find in you",
        tr: "Güven ararım ve sende bulurum",
        ph: "Trast ay siik end ay faynd in yu",
      },
      {
        t: "1.51",
        en: "Every day for us something new",
        tr: "Bizim için her gün yeni bir şey",
        ph: "Evri dey for as samthing nyu",
      },
      {
        t: "1.57",
        en: "Open mind for a different view",
        tr: "Farklı bir bakış için açık bir zihin",
        ph: "Opın maynd for a difrınt vyu",
      },
      {
        t: "2.01",
        en: "And nothing else matters",
        tr: "Ve başka hiçbir şey önemli değil",
        ph: "End nathing els metırz",
      },

      {
        t: "2.09",
        en: "Never cared for what they do",
        tr: "Ne yaptıkları hiç umurumda olmadı",
        ph: "Nevır keerd for vat dey du",
      },
      {
        t: "2.14",
        en: "Never cared for what they know",
        tr: "Ne bildikleri hiç umurumda olmadı",
        ph: "Nevır keerd for vat dey no",
      },
      { t: "2.19", en: "But I know", tr: "Ama ben biliyorum", ph: "Bat ay no" },

      {
        t: "2.25",
        en: "So close, no matter how far",
        tr: "Ne kadar uzak olsak da çok yakın",
        ph: "So klouz, no metır hav far",
      },
      {
        t: "2.31",
        en: "It couldn't be much more from the heart",
        tr: "Daha kalpten olamazdı",
        ph: "It kudınt bi maç mor from dı hart",
      },
      {
        t: "2.36",
        en: "Forever trusting who we are",
        tr: "Kim olduğumuza sonsuz güven",
        ph: "Forevır trasting hu vi ar",
      },
      {
        t: "2.40",
        en: "And nothing else matters",
        tr: "Ve başka hiçbir şey önemli değil",
        ph: "End nathing els metırz",
      },

      {
        t: "2.49",
        en: "Never cared for what they do",
        tr: "Ne yaptıkları hiç umurumda olmadı",
        ph: "Nevır keerd for vat dey du",
      },
      {
        t: "2.54",
        en: "Never cared for what they know",
        tr: "Ne bildikleri hiç umurumda olmadı",
        ph: "Nevır keerd for vat dey no",
      },
      { t: "2.58", en: "But I know", tr: "Ama ben biliyorum", ph: "Bat ay no" },

      {
        t: "3.45",
        en: "I never opened myself this way",
        tr: "Kendimi hiç böyle açmadım",
        ph: "Ay nevır opınd mayself dis vey",
      },
      {
        t: "3.50",
        en: "Life is ours, we live it our way",
        tr: "Hayat bizim, onu kendi yolumuzla yaşarız",
        ph: "Layf iz aorz, vi liv it aur vey",
      },
      {
        t: "3.55",
        en: "All these words, I don't just say",
        tr: "Bu sözlerin hepsi, sadece söylemiyorum",
        ph: "Ol diz vördz, ay dont cast sey",
      },
      {
        t: "4.00",
        en: "And nothing else matters",
        tr: "Ve başka hiçbir şey önemli değil",
        ph: "End nathing els metırz",
      },

      {
        t: "4.08",
        en: "Trust I seek and I find in you",
        tr: "Güven ararım ve sende bulurum",
        ph: "Trast ay siik end ay faynd in yu",
      },
      {
        t: "4.13",
        en: "Every day for us something new",
        tr: "Bizim için her gün yeni bir şey",
        ph: "Evri dey for as samthing nyu",
      },
      {
        t: "4.18",
        en: "Open mind for a different view",
        tr: "Farklı bir bakış için açık bir zihin",
        ph: "Opın maynd for a difrınt vyu",
      },
      {
        t: "4.23",
        en: "And nothing else matters",
        tr: "Ve başka hiçbir şey önemli değil",
        ph: "End nathing els metırz",
      },

      {
        t: "4.31",
        en: "Never cared for what they say",
        tr: "Ne söyledikleri hiç umurumda olmadı",
        ph: "Nevır keerd for vat dey sey",
      },
      {
        t: "4.36",
        en: "Never cared for games they play",
        tr: "Oynadıkları oyunlar hiç umurumda olmadı",
        ph: "Nevır keerd for geymz dey pley",
      },
      {
        t: "4.41",
        en: "Never cared for what they do",
        tr: "Ne yaptıkları hiç umurumda olmadı",
        ph: "Nevır keerd for vat dey du",
      },
      {
        t: "4.46",
        en: "Never cared for what they know",
        tr: "Ne bildikleri hiç umurumda olmadı",
        ph: "Nevır keerd for vat dey no",
      },
      {
        t: "4.51",
        en: "And I know, yeah, yeah",
        tr: "Ve biliyorum, evet, evet",
        ph: "End ay no, yey yey",
      },

      {
        t: "5.25",
        en: "So close, no matter how far",
        tr: "Ne kadar uzak olsak da çok yakın",
        ph: "So klouz, no metır hav far",
      },
      {
        t: "5.30",
        en: "Couldn't be much more from the heart",
        tr: "Kalpten daha fazlası olamazdı",
        ph: "Kudınt bi maç mor from dı hart",
      },
      {
        t: "5.35",
        en: "Forever trusting who we are",
        tr: "Kim olduğumuza sonsuz güven",
        ph: "Forevır trasting hu vi ar",
      },
      {
        t: "5.39",
        en: "No, nothing else matters",
        tr: "Hayır, başka hiçbir şey önemli değil",
        ph: "No, nathing els metırz",
      },
    ],
    tags: ["rock", "classic"],
  },

  {
    slug: "back-to-black",
    title: "Back to Black",
    artist: "Amy Winehouse",
    youtubeId: "TJAfLE39ZZ8",
    lines: [
      {
        t: "0.00",
        en: "He left no time to regret",
        tr: "Pişmanlığa zaman bırakmadı",
        ph: "Hi left no taym tu rigret",
      },
      {
        t: "0.21",
        en: "Kept his dick wet with his same old safe bet",
        tr: "Aynı eski güvenli bahsiyle işini görmeye devam etti",
        ph: "Kept hiz dik wet wid hiz seym old seyf bet",
      },
      {
        t: "0.31",
        en: "Me and my head high",
        tr: "Ben ve dik başım",
        ph: "Mi end may hed hay",
      },
      {
        t: "0.36",
        en: "And my tears dry, get on without my guy",
        tr: "Ve gözyaşlarım kurur, adamım olmadan devam ederim",
        ph: "End may tiirs dray, get on widaout may gay",
      },
      {
        t: "0.46",
        en: "You went back to what you knew",
        tr: "Sen bildiğine geri döndün",
        ph: "Yu went bek tu wat yu nuu",
      },
      {
        t: "0.52",
        en: "So far removed from all that we went through",
        tr: "Geçirdiğimiz her şeyden çok uzakta",
        ph: "So far rimuvd from ol det wi went thruu",
      },
      {
        t: "1.02",
        en: "And I tread a troubled track",
        tr: "Ve sorunlu bir yolda yürüyorum",
        ph: "End ay tred a trabld trek",
      },
      {
        t: "1.08",
        en: "My odds are stacked, I'll go back to black",
        tr: "Şansım tükenmiş, geri dönerim karanlığa",
        ph: "May adz ar stekt, ay'l go bek tu blek",
      },

      {
        t: "1.18",
        en: "We only said goodbye with words",
        tr: "Sadece sözlerle veda ettik",
        ph: "Wi onli sed gudbay wid wördz",
      },
      {
        t: "1.22",
        en: "I died a hundred times",
        tr: "Yüzlerce kez öldüm",
        ph: "Ay dayd a handrəd taymz",
      },
      {
        t: "1.26",
        en: "You go back to her, and I go back to-",
        tr: "Sen ona geri dönersin, ben ise geri dönerim-",
        ph: "Yu go bek tu hör, end ay go bek tu",
      },
      {
        t: "1.33",
        en: "I go back to us",
        tr: "Bize geri dönerim",
        ph: "Ay go bek tu as",
      },

      {
        t: "1.39",
        en: "I love you much",
        tr: "Seni çok seviyorum",
        ph: "Ay lav yu maç",
      },
      {
        t: "1.43",
        en: "It's not enough, you love blow and I love puff",
        tr: "Ama bu yetmez, sen kokaini seversin ben ise esrarı",
        ph: "Its nat inaf, yu lav bloo end ay lav paf",
      },
      {
        t: "1.53",
        en: "And life is like a pipe",
        tr: "Ve hayat bir pipo gibi",
        ph: "End layf iz layk a payp",
      },
      {
        t: "1.58",
        en: "And I'm a tiny penny rollin' up the walls inside",
        tr: "Ve ben iç duvarlarda yuvarlanan küçücük bir madeni para",
        ph: "End ay'm a tayni peni rolin ap de wolz insayd",
      },

      {
        t: "2.09",
        en: "We only said goodbye with words",
        tr: "Sadece sözlerle veda ettik",
        ph: "Wi onli sed gudbay wid wördz",
      },
      {
        t: "2.13",
        en: "I died a hundred times",
        tr: "Yüzlerce kez öldüm",
        ph: "Ay dayd a handrəd taymz",
      },
      {
        t: "2.17",
        en: "You go back to her, and I go back to-",
        tr: "Sen ona geri dönersin, ben ise geri dönerim-",
        ph: "Yu go bek tu hör, end ay go bek tu",
      },

      {
        t: "2.24",
        en: "We only said goodbye with words",
        tr: "Sadece sözlerle veda ettik",
        ph: "Wi onli sed gudbay wid wördz",
      },
      {
        t: "2.28",
        en: "I died a hundred times",
        tr: "Yüzlerce kez öldüm",
        ph: "Ay dayd a handrəd taymz",
      },
      {
        t: "2.32",
        en: "You go back to her, and I go back to-",
        tr: "Sen ona geri dönersin, ben ise geri dönerim-",
        ph: "Yu go bek tu hör, end ay go bek tu",
      },

      { t: "2.44", en: "Black, black", tr: "Kara, kara", ph: "Blek, blek" },
      { t: "2.53", en: "Black, black", tr: "Kara, kara", ph: "Blek, blek" },
      { t: "3.01", en: "Black, black", tr: "Kara, kara", ph: "Blek, blek" },
      { t: "3.10", en: "Black", tr: "Kara", ph: "Blek" },

      {
        t: "3.14",
        en: "I go back to-",
        tr: "Geri dönerim-",
        ph: "Ay go bek tu",
      },
      {
        t: "3.18",
        en: "I go back to-",
        tr: "Geri dönerim-",
        ph: "Ay go bek tu",
      },

      {
        t: "3.22",
        en: "We only said goodbye with words",
        tr: "Sadece sözlerle veda ettik",
        ph: "Wi onli sed gudbay wid wördz",
      },
      {
        t: "3.26",
        en: "I died a hundred times",
        tr: "Yüzlerce kez öldüm",
        ph: "Ay dayd a handrəd taymz",
      },
      {
        t: "3.30",
        en: "You go back to her, and I go back to-",
        tr: "Sen ona geri dönersin, ben ise geri dönerim-",
        ph: "Yu go bek tu hör, end ay go bek tu",
      },

      {
        t: "3.38",
        en: "We only said goodbye with words",
        tr: "Sadece sözlerle veda ettik",
        ph: "Wi onli sed gudbay wid wördz",
      },
      {
        t: "3.42",
        en: "I died a hundred times",
        tr: "Yüzlerce kez öldüm",
        ph: "Ay dayd a handrəd taymz",
      },
      {
        t: "3.45",
        en: "You go back to her, and I go back to black",
        tr: "Sen ona geri dönersin, ben ise karanlığa geri dönerim",
        ph: "Yu go bek tu hör, end ay go bek tu blek",
      },
    ],
    tags: ["soul", "jazz", "pop"],
  },
  {
    slug: "billie-jean",
    title: "Billie Jean",
    artist: "Michael Jackson",
    youtubeId: "Zi_XLOBDo_Y",
    lines: [
      {
        t: "0.00",
        en: "She was more like a beauty queen from a movie scene",
        ph: "şi voz mor layk ı byuti kwiyn from ı muvi siin",
        tr: "Bir film sahnesinden çıkmış güzellik kraliçesine benziyordu",
      },
      {
        t: "0.35",
        en: "I said, \"Don't mind, but what do you mean, I am the one",
        ph: "ay sed, dont maynd, bat vat du yu miin, ay em dı van",
        tr: "Dedim ki, “Sakıncası yok ama ne demek istiyorsun, o kişi ben miyim”",
      },
      {
        t: "0.40",
        en: 'Who will dance on the floor in the round?"',
        ph: "hu vil dens on dı flor in dı raund?",
        tr: "Pistte daire içinde dans edecek olan kim?",
      },
      {
        t: "0.44",
        en: "She said I am the one",
        ph: "şi sed ay em dı van",
        tr: "“O kişi sensin,” dedi",
      },
      {
        t: "0.47",
        en: "Who will dance on the floor in the round",
        ph: "hu vil dens on dı flor in dı raund",
        tr: "Pistte daire içinde dans edecek olan",
      },

      {
        t: "0.55",
        en: "She told me her name was Billie Jean as she caused a scene",
        ph: "şi tould mi hör neym voz bili ciin ez şi kozd ı siin",
        tr: "Adının Billie Jean olduğunu söyledi, ortalığı karıştırırken",
      },
      {
        t: "0.59",
        en: "Then every head turned with eyes that dreamed of bein' the one",
        ph: "den evri hed tönd vid ayz det driimd ov biiin dı van",
        tr: "Sonra herkes başını çevirdi; gözleri o kişi olmayı hayal ediyordu",
      },
      {
        t: "1.04",
        en: "Who will dance on the floor in the round",
        ph: "hu vil dens on dı flor in dı raund",
        tr: "Pistte daire içinde dans edecek olan",
      },

      {
        t: "1.11",
        en: 'People always told me, "Be careful of what you do',
        ph: "pipıl olweyz told mi, bi kerfıl ov vat yu du",
        tr: "İnsanlar bana hep “Ne yaptığına dikkat et” derdi",
      },
      {
        t: "1.15",
        en: "Don't go around breakin' young girls' hearts\" (hee-hee)",
        ph: "dont gou ıraund breykin yang görlz harts (hii-hii)",
        tr: "Genç kızların kalbini kırıp durma (hee-hee)",
      },
      {
        t: "1.19",
        en: 'And mother always told me, "Be careful of who you love',
        ph: "end madır olweyz told mi, bi kerfıl ov hu yu lav",
        tr: "Ve annem hep “Kimi sevdiğine dikkat et” derdi",
      },
      {
        t: "1.23",
        en: "And be careful of what you do (oh-oh)",
        ph: "end bi kerfıl ov vat yu du (o-o)",
        tr: "Ve ne yaptığına dikkat et (oh-oh)",
      },
      {
        t: "1.25",
        en: "'Cause the lie becomes the truth\" (oh-oh), hey-ey",
        ph: "koz dı lay bikamz dı trut (o-o), hey-ey",
        tr: "Çünkü yalan gerçeğe dönüşür (oh-oh), hey-ey",
      },

      {
        t: "1.28",
        en: "Billie Jean is not my lover",
        ph: "bili ciin iz nat may lavır",
        tr: "Billie Jean sevgilim değil",
      },
      {
        t: "1.32",
        en: "She's just a girl who claims that I am the one (oh, baby)",
        ph: "şiz cast ı görl hu kleymz det ay em dı van (oh beybi)",
        tr: "Sadece “o kişi sensin” diyen bir kız (ah, bebeğim)",
      },
      {
        t: "1.36",
        en: "But the kid is not my son (hoo)",
        ph: "bat dı kid iz nat may san (huu)",
        tr: "Ama o çocuk benim oğlum değil (hoo)",
      },
      {
        t: "1.42",
        en: "She says I am the one (oh, baby)",
        ph: "şi sez ay em dı van (oh beybi)",
        tr: "“O kişi sensin,” diyor (ah, bebeğim)",
      },
      {
        t: "1.45",
        en: "But the kid is not my son (hee-hee-hee, no-no, hee-hee-hee, hoo)",
        ph: "bat dı kid iz nat may san (hii-hii-hii, no-no, hii-hii-hii, huu)",
        tr: "Ama çocuk benim oğlum değil (hee-hee-hee, hayır-hayır, hee-hee-hee, hoo)",
      },

      {
        t: "1.53",
        en: "For forty days and for forty nights, law was on her side",
        ph: "for forti deyz end for forti nayts, lo voz on hör sayd",
        tr: "Kırk gün kırk gece boyunca yasa ondan yanaydı",
      },
      {
        t: "1.56",
        en: "But who can stand when she's in demand? Her schemes and plans",
        ph: "bat hu ken stend ven şiz in dimend? hör skiimz end plänz",
        tr: "Ama o rağbet görürken kim dayanabilir? Hileleri ve planları",
      },
      {
        t: "2.02",
        en: "'Cause we danced on the floor in the round (hee)",
        ph: "koz vi densd on dı flor in dı raund (hii)",
        tr: "Çünkü pistte daire içinde dans ettik (hee)",
      },
      {
        t: "2.06",
        en: "So take my strong advice",
        ph: "so teyk may strong edvays",
        tr: "Bu yüzden sağlam öğüdümü tut",
      },
      {
        t: "2.10",
        en: "Just remember to always think twice",
        ph: "cast rimembır tu olweyz tink tıvays",
        tr: "Her zaman iki kere düşünmeyi unutma",
      },
      {
        t: "2.14",
        en: "(Do think twice) do think twice (ah-hoo)",
        ph: "(du tink tıvays) du tink tıvays (a-hu)",
        tr: "(İki kere düşün) iki kere düşün (ah-hoo)",
      },

      {
        t: "2.17",
        en: "She told my baby we'd danced 'til three, then she looked at me",
        ph: "şi tould may beybi vid densd til tri, den şi lukt et mi",
        tr: "Bebeğime üçe kadar dans ettiğimizi söyledi, sonra bana baktı",
      },
      {
        t: "2.22",
        en: "Then showed a photo of a baby cryin', his eyes were like mine (oh, no)",
        ph: "den şoud ı foto ov ı beybi krayin, hiz ayz vö layk mayn (oh no)",
        tr: "Sonra ağlayan bir bebeğin fotoğrafını gösterdi, gözleri benimkine benziyordu (ah, hayır)",
      },
      {
        t: "2.26",
        en: "Go and dance on the floor in the round, baby (ooh, hee-hee-hee)",
        ph: "go end dens on dı flor in dı raund, beybiy (uu, hii-hii-hii)",
        tr: "Git ve pistte daire içinde dans et, bebeğim (ooh, hee-hee-hee)",
      },

      {
        t: "2.33",
        en: 'People always told me, "Be careful of what you do',
        ph: "pipıl olweyz told mi, bi kerfıl ov vat yu du",
        tr: "İnsanlar bana hep “Ne yaptığına dikkat et” derdi",
      },
      {
        t: "2.37",
        en: "And don't go around breakin' young girls' hearts\" (don't break no hearts, hee-hee)",
        ph: "end dont gou ıraund breykin yang görlz harts (dont breyk no harts, hii-hii)",
        tr: "Ve genç kızların kalbini kırma (kalp kırma, hee-hee)",
      },
      {
        t: "2.41",
        en: "But she came and stood right by me",
        ph: "bat şi keym end stud rayt bay mi",
        tr: "Ama geldi ve tam yanımda durdu",
      },
      {
        t: "2.43",
        en: "Just the smell of sweet perfume",
        ph: "cast dı smel ov svit pörfyum",
        tr: "Sadece tatlı bir parfüm kokusu",
      },
      {
        t: "2.46",
        en: "This happened much too soon",
        ph: "dis heppınd maç tu sun",
        tr: "Bu çok erken oldu",
      },
      {
        t: "2.48",
        en: "She called me to her room, hey-ey",
        ph: "şi kold mi tu hör rum, hey-ey",
        tr: "Beni odasına çağırdı, hey-ey",
      },

      {
        t: "2.50",
        en: "Billie Jean is not my lover (hoo)",
        ph: "bili ciin iz nat may lavır (huu)",
        tr: "Billie Jean sevgilim değil (hoo)",
      },
      {
        t: "2.53",
        en: "She's just a girl who claims that I am the one",
        ph: "şiz cast ı görl hu kleymz det ay em dı van",
        tr: "Sadece “o kişi sensin” diyen bir kız",
      },
      {
        t: "2.59",
        en: "But the kid is not my son",
        ph: "bat dı kid iz nat may san",
        tr: "Ama çocuk benim oğlum değil",
      },
      {
        t: "3.02",
        en: "No-no-no, no-no, no-no-no (hoo)",
        ph: "no-no-no, no-no, no-no-no (huu)",
        tr: "Hayır-hayır-hayır, hayır-hayır, hayır-hayır-hayır (hoo)",
      },

      {
        t: "3.06",
        en: "Billie Jean is not my lover",
        ph: "bili ciin iz nat may lavır",
        tr: "Billie Jean sevgilim değil",
      },
      {
        t: "3.10",
        en: "She's just a girl who claims that I am the one (oh, baby)",
        ph: "şiz cast ı görl hu kleymz det ay em dı van (oh beybi)",
        tr: "Sadece “o kişi sensin” diyen bir kız (ah, bebeğim)",
      },
      {
        t: "3.15",
        en: "But the kid is not my son (no, no)",
        ph: "bat dı kid iz nat may san (no, no)",
        tr: "Ama çocuk benim oğlum değil (hayır, hayır)",
      },
      {
        t: "3.21",
        en: "She says I am the one (oh, baby)",
        ph: "şi sez ay em dı van (oh beybi)",
        tr: "“O kişi sensin,” diyor (ah, bebeğim)",
      },
      {
        t: "3.23",
        en: "But the kid is not my son (no, hee-hee-ho, hee-hee-hee)",
        ph: "bat dı kid iz nat may san (no, hii-hii-ho, hii-hii-hii)",
        tr: "Ama çocuk benim oğlum değil (hayır, hee-hee-ho, hee-hee-hee)",
      },

      { t: "3.30", en: "Hee, hoo", ph: "hii, huu", tr: "hee, hoo" },
      {
        t: "3.45",
        en: "She says I am the one",
        ph: "şi sez ay em dı van",
        tr: "“O kişi sensin,” diyor",
      },
      {
        t: "3.49",
        en: "But the kid is not my son (no-no-no, hoo, oh)",
        ph: "bat dı kid iz nat may san (no-no-no, huu, o)",
        tr: "Ama çocuk benim oğlum değil (hayır-hayır-hayır, hoo, oh)",
      },

      {
        t: "3.55",
        en: "Billie Jean is not my lover",
        ph: "bili ciin iz nat may lavır",
        tr: "Billie Jean sevgilim değil",
      },
      {
        t: "4.00",
        en: "She's just a girl who claims that I am the one (you know what you did to me, baby)",
        ph: "şiz cast ı görl hu kleymz det ay em dı van (yu nou vat yu did tu mi, beybi)",
        tr: "Sadece “o kişi sensin” diyen bir kız (bana ne yaptığını biliyorsun, bebeğim)",
      },
      {
        t: "4.06",
        en: "But the kid is not my son",
        ph: "bat dı kid iz nat may san",
        tr: "Ama çocuk benim oğlum değil",
      },
      {
        t: "4.08",
        en: "No-no-no (no-no-no, ah), no-no-no-no (no-no-no)",
        ph: "no-no-no (no-no-no, a), no-no-no-no (no-no-no)",
        tr: "Hayır-hayır-hayır (hayır-hayır-hayır, ah), hayır-hayır-hayır-hayır (hayır-hayır-hayır)",
      },
      {
        t: "4.10",
        en: "She says I am the one (no)",
        ph: "şi sez ay em dı van (no)",
        tr: "“O kişi sensin,” diyor (hayır)",
      },
      {
        t: "4.14",
        en: "But the kid is not my son (no-no-no-no)",
        ph: "bat dı kid iz nat may san (no-no-no-no)",
        tr: "Ama çocuk benim oğlum değil (hayır-hayır-hayır-hayır)",
      },
      {
        t: "4.18",
        en: "She says I am the one (you know what you did)",
        ph: "şi sez ay em dı van (yu nou vat yu did)",
        tr: "“O kişi sensin,” diyor (ne yaptığını biliyorsun)",
      },
      {
        t: "4.22",
        en: "She says he is my son (breakin' my heart, babe)",
        ph: "şi sez hi iz may san (brekin may hart, beyib)",
        tr: "“O benim oğlum,” diyor (kalbimi kırıyorsun, bebeğim)",
      },
      {
        t: "4.27",
        en: "She says I am the one",
        ph: "şi sez ay em dı van",
        tr: "“O kişi sensin,” diyor",
      },

      {
        t: "4.29",
        en: "Billie Jean is not my lover",
        ph: "bili ciin iz nat may lavır",
        tr: "Billie Jean sevgilim değil",
      },
      {
        t: "4.33",
        en: "Billie Jean is not my lover",
        ph: "bili ciin iz nat may lavır",
        tr: "Billie Jean sevgilim değil",
      },
      {
        t: "4.37",
        en: "Billie Jean is not my lover",
        ph: "bili ciin iz nat may lavır",
        tr: "Billie Jean sevgilim değil",
      },
      {
        t: "4.41",
        en: "Billie Jean is not my lover (don't call me Billie Jean, hoo)",
        ph: "bili ciin iz nat may lavır (dont kol mi bili ciin, huu)",
        tr: "Billie Jean sevgilim değil (bana Billie Jean deme, hoo)",
      },
      {
        t: "4.45",
        en: "Billie Jean is not my lover",
        ph: "bili ciin iz nat may lavır",
        tr: "Billie Jean sevgilim değil",
      },
      {
        t: "4.49",
        en: "Billie Jean is not- (hee)",
        ph: "bili ciin iz nat- (hii)",
        tr: "Billie Jean sevgilim değ- (hee)",
      },
    ],
    tags: ["pop", "80s", "mj"],
  },
  {
    slug: "shape-of-my-heart",
    title: "Shape of My Heart",
    artist: "Sting",
    youtubeId: "QK-Z1K67uaA",
    lines: [
      {
        t: "0.00",
        en: "He deals the cards as a meditation",
        ph: "hi diylz dı kardz ez ı mediteyşın",
        tr: "Kartları bir meditasyon gibi dağıtır",
      },
      {
        t: "0.29",
        en: "And those he plays never suspect",
        ph: "end doz hi pleyz nevır sısp ekt",
        tr: "Ve onunla oynayanlar asla şüphelenmez",
      },
      {
        t: "0.35",
        en: "He doesn't play for the money he wins",
        ph: "hi dazınt pley for dı mani hi vinz",
        tr: "Kazandığı para için oynamaz",
      },
      {
        t: "0.41",
        en: "He don't play for respect",
        ph: "hi dont pley for rispekt",
        tr: "Saygı kazanmak için oynamaz",
      },
      {
        t: "0.47",
        en: "He deals the cards to find the answer",
        ph: "hi diylz dı kardz tu faynd di ensır",
        tr: "Cevabı bulmak için kartları dağıtır",
      },
      {
        t: "0.53",
        en: "The sacred geometry of chance",
        ph: "dı seykırd ciomıtri ov çens",
        tr: "Şansın kutsal geometrisi",
      },
      {
        t: "0.58",
        en: "The hidden law of a probable outcome",
        ph: "dı hidın lo ov ı probıbıl autkam",
        tr: "Muhtemel bir sonucun gizli yasası",
      },
      {
        t: "1.04",
        en: "The numbers lead a dance",
        ph: "dı nambırz liid ı dens",
        tr: "Sayılar bir dansı yönetir",
      },

      {
        t: "1.09",
        en: "I know that the spades are the swords of a soldier",
        ph: "ay nou det dı speydz ar dı sordz ov ı solcır",
        tr: "Maçaların bir askerin kılıçları olduğunu biliyorum",
      },
      {
        t: "1.15",
        en: "I know that the clubs are weapons of war",
        ph: "ay nou det dı klabz ar vepınz ov vor",
        tr: "Sineklerin savaş silahları olduğunu biliyorum",
      },
      {
        t: "1.21",
        en: "I know that diamonds mean money for this art",
        ph: "ay nou det daymındz miin mani for dis art",
        tr: "Karoların bu sanat için parayı temsil ettiğini biliyorum",
      },
      {
        t: "1.26",
        en: "But that's not the shape of my heart",
        ph: "bat dets nat dı şeyp ov may hart",
        tr: "Ama kalbimin şekli bu değil",
      },

      {
        t: "1.33",
        en: "He may play the jack of diamonds",
        ph: "hi mey pley dı cek ov daymındz",
        tr: "Karo valeyi oynayabilir",
      },
      {
        t: "1.39",
        en: "He may lay the queen of spades",
        ph: "hi mey ley dı kuinn ov speydz",
        tr: "Maça kraliçeyi koyabilir",
      },
      {
        t: "1.43",
        en: "He may conceal a king in his hand",
        ph: "hi mey kınsiil ı king in hiz hend",
        tr: "Elinde bir kral saklayabilir",
      },
      {
        t: "1.50",
        en: "While the memory of it fades",
        ph: "vayl dı memri ov it feydz",
        tr: "Bunun anısı silinirken",
      },

      {
        t: "155",
        en: "I know that the spades are the swords of a soldier",
        ph: "ay nou det dı speydz ar dı sordz ov ı solcır",
        tr: "Maçaların bir askerin kılıçları olduğunu biliyorum",
      },
      {
        t: "2.01",
        en: "I know that the clubs are weapons of war",
        ph: "ay nou det dı klabz ar vepınz ov vor",
        tr: "Sineklerin savaş silahları olduğunu biliyorum",
      },
      {
        t: "2.06",
        en: "I know that diamonds mean money for this art",
        ph: "ay nou det daymındz miin mani for dis art",
        tr: "Karoların bu sanat için parayı temsil ettiğini biliyorum",
      },
      {
        t: "2.11",
        en: "But that's not the shape of my heart",
        ph: "bat dets nat dı şeyp ov may hart",
        tr: "Ama kalbimin şekli bu değil",
      },
      {
        t: "2.17",
        en: "That's not the shape",
        ph: "dets nat dı şeyp",
        tr: "Bu şekil değil",
      },
      {
        t: "2.23",
        en: "The shape of my heart",
        ph: "dı şeyp ov may hart",
        tr: "Kalbimin şekli",
      },

      {
        t: "2.55",
        en: "If I told her that I loved you",
        ph: "if ay tould hör det ay lavd yu",
        tr: "Eğer ona seni sevdiğimi söylesem",
      },
      {
        t: "3.00",
        en: "You'd maybe think there's something wrong",
        ph: "yud meybi tink derz samting rong",
        tr: "Belki bir terslik olduğunu düşünürdün",
      },
      {
        t: "3.05",
        en: "I'm not a man of too many faces",
        ph: "aym nat ı men ov tu meni feysız",
        tr: "Çok fazla yüzü olan bir adam değilim",
      },
      {
        t: "3.12",
        en: "The mask I wear is one",
        ph: "dı mesk ay veır iz van",
        tr: "Taktığım maske tektir",
      },
      {
        t: "3.17",
        en: "But those who speak know nothing",
        ph: "bat doz hu spiik nou nathing",
        tr: "Ama konuşanlar hiçbir şey bilmez",
      },
      {
        t: "3.23",
        en: "And find out to their cost",
        ph: "end faynd aut tu deır kost",
        tr: "Ve bedelini ödeyerek öğrenirler",
      },
      {
        t: "3.28",
        en: "Like those who curse their luck in too many places",
        ph: "layk doz hu körs deır lak in tu meni pleysız",
        tr: "Pek çok yerde şansına lanet edenler gibi",
      },
      {
        t: "3.35",
        en: "And those who fear are lost",
        ph: "end doz hu fiır ar lost",
        tr: "Ve korkanlar kaybolur",
      },

      {
        t: "3.40",
        en: "I know that the spades are the swords of a soldier",
        ph: "ay nou det dı speydz ar dı sordz ov ı solcır",
        tr: "Maçaların bir askerin kılıçları olduğunu biliyorum",
      },
      {
        t: "3.45",
        en: "I know that the clubs are weapons of war",
        ph: "ay nou det dı klabz ar vepınz ov vor",
        tr: "Sineklerin savaş silahları olduğunu biliyorum",
      },
      {
        t: "3.50",
        en: "I know that diamonds mean money for this art",
        ph: "ay nou det daymındz miin mani for dis art",
        tr: "Karoların bu sanat için parayı temsil ettiğini biliyorum",
      },
      {
        t: "3.56",
        en: "But that's not the shape of my heart",
        ph: "bat dets nat dı şeyp ov may hart",
        tr: "Ama kalbimin şekli bu değil",
      },
      {
        t: "4.01",
        en: "That's not the shape of my heart",
        ph: "dets nat dı şeyp ov may hart",
        tr: "Bu, kalbimin şekli değil",
      },
      {
        t: "4.07",
        en: "That's not the shape",
        ph: "dets nat dı şeyp",
        tr: "Bu şekil değil",
      },
      {
        t: "4.13",
        en: "The shape of my heart",
        ph: "dı şeyp ov may hart",
        tr: "Kalbimin şekli",
      },
    ],
    tags: ["pop", "90s", "sting"],
  },
  {
  slug: "what-a-wonderful-world",
  title: "What a Wonderful World",
  artist: "Louis Armstrong",
  youtubeId: "CWzrABouyeE",
  lines: [
    {
      t: "0.00",
      en: "I see trees of green, red roses too",
      ph: "ay sii triiz of griin, red rouziz tuu",
      tr: "Yeşil ağaçlar görüyorum, kırmızı güller de",
    },
    {
      t: "0.14",
      en: "I see them bloom for me and you",
      ph: "ay sii dem bluum for mi end yu",
      tr: "Benim ve senin için açtıklarını görüyorum",
    },
    {
      t: "0.20",
      en: "And I think to myself, what a wonderful world",
      ph: "end ay tink tu mayself, vat a vandırfıl vörld",
      tr: "Ve kendi kendime diyorum ki, ne harika bir dünya",
    },
    {
      t: "0.33",
      en: "I see skies of blue and clouds of white",
      ph: "ay sii skayz of bluu end klauudz of vayt",
      tr: "Mavi gökyüzü ve beyaz bulutlar görüyorum",
    },
    {
      t: "0.41",
      en: "The bright blessed day, the dark sacred night",
      ph: "dı brayt blesd dey, dı dark seykırd nayt",
      tr: "Parlak kutsanmış gün, karanlık kutsal gece",
    },
    {
      t: "0.47",
      en: "And I think to myself, what a wonderful world",
      ph: "end ay tink tu mayself, vat a vandırfıl vörld",
      tr: "Ve kendi kendime diyorum ki, ne harika bir dünya",
    },
    {
      t: "1.01",
      en: "The colors of the rainbow, so pretty in the sky",
      ph: "dı kalırz of dı reynbou, so priti in dı skay",
      tr: "Gökkuşağının renkleri, gökyüzünde çok güzel",
    },
    {
      t: "1.07",
      en: "Are also on the faces of people going by",
      ph: "ar olsou on dı feysiz of piipıl gouing bay",
      tr: "Yoldan geçen insanların yüzlerinde de var",
    },
    {
      t: "1.13",
      en: "I see friends shaking hands, saying 'How do you do?'",
      ph: "ay sii frendz şeyking hends, seying hav du yu du",
      tr: "Arkadaşların el sıkıştığını, 'Nasılsın?' dediklerini görüyorum",
    },
    {
      t: "1.21",
      en: "They're really saying, 'I love you'",
      ph: "deyr rili seying, ay lav yu",
      tr: "Aslında 'Seni seviyorum' diyorlar",
    },
    {
      t: "1.27",
      en: "I hear babies cry, I watch them grow",
      ph: "ay hiir beybiiz kray, ay voç dem grou",
      tr: "Bebeklerin ağladığını duyuyorum, büyüdüklerini izliyorum",
    },
    {
      t: "1.34",
      en: "They'll learn much more than I'll ever know",
      ph: "deyl lörn maç mor den ayl evır nou",
      tr: "Benden çok daha fazlasını öğrenecekler",
    },
    {
      t: "1.40",
      en: "And I think to myself, what a wonderful world",
      ph: "end ay tink tu mayself, vat a vandırfıl vörld",
      tr: "Ve kendi kendime diyorum ki, ne harika bir dünya",
    },
    {
      t: "1.52",
      en: "Yes, I think to myself, what a wonderful world",
      ph: "yes, ay tink tu mayself, vat a vandırfıl vörld",
      tr: "Evet, kendi kendime diyorum ki, ne harika bir dünya",
    },
    {
      t: "2.10",
      en: "Ooh, yes",
      ph: "uh, yes",
      tr: "Ah, evet",
    },
  ],
  tags: ["jazz", "classic"]
}

];
